//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_LTCSDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LaptopPCSaleDBEntities : DbContext
    {
        public LaptopPCSaleDBEntities()
            : base("name=LaptopPCSaleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<LayDSCTDonHang_Result> LayDSCTDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDSCTDonHang_Result>("LayDSCTDonHang");
        }
    
        public virtual ObjectResult<LayDSDonHang_Result> LayDSDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDSDonHang_Result>("LayDSDonHang");
        }
    
        public virtual ObjectResult<Nullable<int>> orderDetail_KTCTDonHang(Nullable<int> orderID, Nullable<int> productID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("orderDetail_KTCTDonHang", orderIDParameter, productIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> user_KTDangNhap(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("user_KTDangNhap", usernameParameter, passwordParameter);
        }
    }
}
